### ISSUE TITLE
Unable to find ic_documents_filled icon

### ISSUE THREAD

**Issue by wahibhaq** [codernaut/citizenconnect#19]
I have the latest code from `codernaut:master` and after fixing the libs/mail.jar issue I got another build error because this icon doesn't exist in drawable but it is referred in `MainActivity.java:69`. 

```
AHBottomNavigationItem item2 = new AHBottomNavigationItem(R.string.bottom_item2, R.drawable.ic_documents_filled, R.color.colorPrimary);

```
In the production app, I can see that this is a *Services* tab but can't find the icon used. 

@shahzaib414 did you push it? I went through the code in this repo and also couldn't find.

**Comment by shahzaib414** [comment]
i added that file just know , please check

**Comment by wahibhaq** [comment]
@shahzaib414 thanks for responding but I expected that you will create a separate PR for adding this image as it has nothing to do with with this PR of Model Crash https://github.com/codernaut/citizenconnect/pull/16 

Can you create a separate one and also better added the icon in `drawable/hdpi` like the rest of icons.

**Comment by shahzaib414** [comment]
i have pushed latest code and created PR for that , please check
