### ISSUE TITLE
Integrate proper .gitignore for more clean repo without unnecessary files

### ISSUE THREAD

**Issue by wahibhaq** [codernaut/citizenconnect#6]
I can see a lot of unnecessary files which could be avoided if there is a proper .gitignore file in use. 

For starting, we can use it from one of my projects https://github.com/wahibhaq/urdu-font-comparator-app/blob/master/.gitignore and further improve it if needed.

**Comment by codernaut** [comment]
go ahead

**Comment by wahibhaq** [comment]
completed and merged https://github.com/codernaut/citizenconnect/pull/14
